apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ipuz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-ipuz@sha256:356d55069d2aeb753dd42c179e56024b1b6b7614e01c8d47c156acc82b101b0f
        name: my-nodejs
        resources: {}
status: {}
